# Generated by Django 5.2.3 on 2025-09-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('from_account', models.CharField(max_length=200)),
                ('to_account', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('risk_score', models.FloatField(default=0.0)),
                ('flags', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('suspicious', 'Suspicious'), ('flagged', 'Flagged')], default='normal', max_length=20)),
            ],
        ),
    ]
